"""Data structures and contracts transferred between stages of the Retrieval Pipeline."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class Query(BaseModel):
    """Represents the incoming search query with execution parameters."""
    raw_query: str
    transformed_query: Optional[str] = None
    top_k: int = 5
    filters: Dict[str, Any] = Field(default_factory=dict)


class RetrievedChunk(BaseModel):
    """Represents a candidate text chunk retrieved from the vector store."""
    chunk_id: str
    payload_id: str
    payload_version: int
    chunk_index: int
    chunk_text: str
    score: float
    rerank_score: Optional[float] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class RetrievalResult(BaseModel):
    """Output wrapper containing query context and retrieved/reranked candidate chunks."""
    query: Query
    chunks: List[RetrievedChunk] = Field(default_factory=list)


class SynthesizedResponse(BaseModel):
    """Final output generated by the RAG pipeline."""
    query: str
    answer: str
    cited_chunks: List[RetrievedChunk] = Field(default_factory=list)
    execution_metadata: Dict[str, Any] = Field(default_factory=dict)