"""add is_purged to text_chunks

Revision ID: 3d9845bc5b97
Revises: 759d927f8ff9
Create Date: 2026-09-11 09:07:31.758348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9845bc5b97'
down_revision: Union[str, Sequence[str], None] = '759d927f8ff9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_chunks', sa.Column('is_purged', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_chunks', 'is_purged')
    # ### end Alembic commands ###
